backend:
  name: git-gateway
  branch: main

media_folder: "uploads"
public_folder: "src/uploads"

publish_mode: editorial_workflow

site_url: https://minimal-decap-cms.netlify.app/

collections:
  - name: "collection"
    label: "Collection"
    editor:
      preview: false
    folder: "app/collections"
    create: true
    slug: "{{slug}}"
    format: json
    fields:
      - name: "name"
        label: "Collection Title"
        widget: string
        required: true

      - name: "fields"
        label: "Collection Fields"
        widget: list
        collapsed: true
        fields:
          - name: name
            label: Name
            widget: string
            required: true

          - name: widget
            label: Type
            widget: select
            required: true
            options: [Boolean, Code, Color, DateTime, File, Hidden, Image, List, Map, Markdown, Number, Object, Relation, Select, String, Text]

          - name: required
            label: Required
            widget: boolean
            required: false

          - name: hint
            label: Hint
            widget: markdown
            required: false
          

          - name: options
            label: Options
            widget: list
            collapsed: true
            fields:
              - name: config
                label: Config
                widget: code
                default_language: "yaml"
                allow_language_selection: false
                output_code_only: true
            