[build]
  base = ""  
  command = "npm run build"  
  publish = "src"
  

[[redirects]]
  from = "/*"
  to = "404.json"
  status = 404

[identity]
  enabled = true
  autoConfirm = true
  roles = ["admin"]

[identity.gateways]
  git_gateway = true