backend:
  name: git-gateway
  branch: main
media_folder: uploads
public_folder: build/uploads
collections:
  - name: blog
    label: Blog
    editor:
      preview: false
    folder: src/blog/entries
    create: true
    slug: '{{slug}}'
    format: json
    fields:
      - name: content
        label: Content
        widget: markdown
