backend:
  name: git-gateway
  branch: main

media_folder: "uploads"
public_folder: "src/uploads"

collections:
  - name: "collection"
    label: "Collection"
    editor:
      preview: false
    folder: "src/collections"
    create: true
    slug: "{{slug}}"
    format: json
    fields:
      - name: "name"
        label: "Collection Title"
        widget: string

      - name: "fields"
        label: "Collection Fields"
        widget: code
        default_language: yml