backend:
  name: git-gateway
  branch: main
media_folder: src/uploads
public_folder: uploads
collections:
  - name: blog
    label: Blog
    editor:
      preview: false
    folder: src/blog/entries
    create: true
    slug: '{{name}}'
    format: json
    fields:
      - name: title
        label: Title
        widget: string
        required: true
      - name: content
        label: Content
        widget: markdown
  - name: events
    label: Events
    editor:
      preview: false
    folder: src/events/entries
    create: true
    slug: '{{name}}'
    format: json
    fields:
      - name: title
        label: Title
        widget: string
        required: true
      - name: date
        label: Date
        widget: dateTime
  - name: testimonial
    label: Testimonial
    editor:
      preview: false
    folder: src/testimonial/entries
    create: true
    slug: '{{name}}'
    format: json
    fields:
      - name: title
        label: Title
        widget: string
        required: true
      - name: name
        label: Name
        widget: string
